server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://39.105.132.36:10088/peaceworld?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2t#svzPYp3RS
    #如果是老版本的MySql,或者手动修改my.ini指定加密方式为mysql_native_password,则使用原来的Driver即可
    #driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 30
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: SELECT 'x'
      remove-abandoned: true
      remove-abandoned-timeout: 2800
      filters: stat,wall
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: root
        login-password: root
        aop-patterns: com.chc.peaceworld.*.service.*
  output:
    ansi:
      enabled: detect
  aop:
    proxy-target-class: true
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:repository/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.chc.peaceworld.*.entity
  #配置扫描通用枚举
  typeEnumsPackage: com.chc.peaceworld.*.*
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      chc:
        peaceworld: debug
  config: classpath:log/logback-spring.xml
jwt:
  header: Authorization
  secret: peaceworld
  expiration: 604800
  tokenHead: "Bearer "

